# Generated by Django 4.2.2 on 2023-08-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('nrc', models.CharField(blank=True, max_length=14)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('desired_program', models.CharField(choices=[('Introduction to Business Management', 'Introduction to Business Management'), ('Fundamentals of Accounting', 'Fundamentals of Accounting'), ('Marketing and Sales Management', 'Marketing and Sales Management'), ('Human Resource Management', 'Human Resource Management'), ('Entrepreneurship and Innovation', 'Entrepreneurship and Innovation'), ('Project Management', 'Project Management'), ('Financial Management', 'Financial Management'), ('Introduction to Information Technology', 'Introduction to Information Technology'), ('Website Design and Development', 'Website Design and Development'), ('Database Design and Management', 'Database Design and Management'), ('Cybersecurity and Ethical Hacking', 'Cybersecurity and Ethical Hacking'), ('Network Administration and Management', 'Network Administration and Management'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Graphic Designing', 'Graphic Designing'), ('Digital Art and Illustration', 'Digital Art and Illustration'), ('Photography', 'Photography'), ('Film and Television Production', 'Film and Television Production'), ('Animation and Visual Effects', 'Animation and Visual Effects'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
